/* OpenDrop v0.3.0 — no external browser scripts or runtime packages. */
'use strict';
const API='https://jxsbgblbmkfnzgtnaata.supabase.co/functions/v1/opendrop-api';
const MAX=524288000,VERSION='0.3.0';
const $=s=>document.querySelector(s),T=OpenDropTransfer;
let queue=[],files=[],selected=new Set(),busy=false,uploadPassword='',clockOffset=0,searchTimer,loadSerial=0,previewFile=null,previewUrls=[];
const accessCache=new Map();let passwordTask=null,confirmTask=null;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID();
const pause=ms=>new Promise(r=>setTimeout(r,ms));
function bytes(value){let n=Number(value),i=0;const units=['B','KB','MB','GB'];while(n>=1024&&i<3){n/=1024;i++;}return(n>=100||!i?n.toFixed(0):n.toFixed(1))+' '+units[i];}
function remaining(s){const sec=Math.max(0,Math.ceil((Date.parse(s)-Date.now()-clockOffset)/1000));if(!sec)return'만료됨';if(sec<60)return sec+'초';const m=Math.ceil(sec/60);return m<60?m+'분':Math.floor(m/60)+'시간'+(m%60?' '+m%60+'분':'');}
function toast(text){const el=$('#toast');el.textContent=text;el.hidden=false;clearTimeout(el._timer);el._timer=setTimeout(()=>el.hidden=true,4500);}
function report(error,stage='처리'){if(error?.name==='AbortError')return;$('#errorBox').hidden=false;$('#errorSummary').textContent=stage+': '+(error.message||'처리하지 못했습니다.');$('#errorDetail').textContent=['OpenDrop '+VERSION,'단계: '+(error.stage||stage),'코드: '+(error.code||'UNKNOWN'),'HTTP: '+(error.status||'응답 없음'),'요청 ID: '+(error.requestId||'-'),'온라인: '+navigator.onLine,'브라우저: '+navigator.userAgent].join('\n');}
async function api(path,data,opts={}){const attempts=opts.retry===false?1:(data===undefined?3:1);let last;for(let i=0;i<attempts;i++){if(i)await pause(600*i);const c=new AbortController(),timer=setTimeout(()=>c.abort(),30000);try{const r=await fetch(API+'/'+path,{method:data===undefined?'GET':'POST',credentials:'omit',cache:'no-store',headers:data===undefined?{}:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data),signal:c.signal});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.error||'서버 요청 실패 (HTTP '+r.status+')');Object.assign(e,{status:r.status,code:d.code,stage:d.stage||path.split('?')[0],requestId:d.requestId});throw e;}if(d.serverTime)clockOffset=Date.parse(d.serverTime)-Date.now();return d;}catch(e){last=e;if(e.status&&e.status<500)throw e;if(!e.status){last=new Error(navigator.onLine?'서버와 연결하지 못했습니다. 연결을 확인한 후 재시도해 주세요.':'인터넷 연결이 끊겼습니다. 연결 후 재시도해 주세요.');Object.assign(last,{code:c.signal.aborted?'TIMEOUT':'NETWORK',stage:path.split('?')[0]});}}finally{clearTimeout(timer);}}throw last;}
const workerReady=(async()=>{if(!('serviceWorker'in navigator)||!isSecureContext)return null;try{const r=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});await Promise.race([navigator.serviceWorker.ready,pause(8000).then(()=>{throw Error('worker timeout');})]);if(!navigator.serviceWorker.controller)await Promise.race([new Promise(resolve=>navigator.serviceWorker.addEventListener('controllerchange',resolve,{once:true})),pause(2500)]);return navigator.serviceWorker.controller||r.active;}catch{return null;}})();
navigator.serviceWorker?.addEventListener('message',e=>{if(e.data?.type==='transfer-error')report(new Error(e.data.message),'다운로드');});
function openDialog(id){const d=$(id);if(!d.open)d.showModal();}
for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>$('#'+b.dataset.close).close();
function cancelled(){return new DOMException('취소되었습니다.','AbortError');}
function passwordDialog(mode,file){if(passwordTask)return Promise.reject(new Error('열려 있는 비밀번호 창을 먼저 닫아 주세요.'));return new Promise((resolve,reject)=>{passwordTask={mode,file,resolve,reject};$('#passwordTitle').textContent=mode==='set'?'[#] 업로드 비밀번호':'[#] 잠긴 파일';$('#passwordDescription').textContent=mode==='set'?'대기 중인 파일에 적용할 비밀번호를 설정하세요. 파일 이름은 목록에 공개됩니다.':file.name+' — 파일을 열려면 비밀번호가 필요합니다.';$('#passwordValue').value=mode==='set'?uploadPassword:'';$('#passwordValue').type='password';$('#passwordValue').autocomplete=mode==='set'?'new-password':'current-password';$('#showPassword').checked=false;$('#passwordError').textContent='';$('#removePasswordBtn').hidden=mode!=='set';$('#passwordSubmit').textContent=mode==='set'?'적용':'잠금 해제';$('#passwordSubmit').disabled=false;openDialog('#passwordDialog');setTimeout(()=>$('#passwordValue').focus(),30);});}
$('#passwordDialog').addEventListener('close',()=>{const task=passwordTask;passwordTask=null;$('#passwordValue').value='';if(task)task.reject(cancelled());});
$('#showPassword').onchange=e=>$('#passwordValue').type=e.target.checked?'text':'password';
function finishPassword(value){const t=passwordTask;passwordTask=null;$('#passwordDialog').close();t?.resolve(value);}
$('#passwordForm').onsubmit=async e=>{e.preventDefault();const t=passwordTask;if(!t)return;const value=$('#passwordValue').value;$('#passwordError').textContent='';$('#passwordSubmit').disabled=true;try{if(t.mode==='set')finishPassword(value);else{if(!value)throw new Error('비밀번호를 입력해 주세요.');const a=await api('access',{fileId:t.file.id,password:value});accessCache.set(t.file.id,a);finishPassword(a);}}catch(err){$('#passwordError').textContent=err.message;}finally{$('#passwordSubmit').disabled=false;}};
$('#removePasswordBtn').onclick=()=>finishPassword('');
function updateOptions(){const ttl=Number($('#ttlSelect').value),label=ttl===600?'10m':(ttl/3600)+'h';$('#commandOptions').textContent='--ttl '+label+(uploadPassword?' --locked':' --public');$('#setPasswordBtn').textContent=uploadPassword?'[x] 비밀번호 설정됨':'[ ] 비밀번호 없음';}
$('#setPasswordBtn').onclick=async()=>{try{uploadPassword=await passwordDialog('set');updateOptions();}catch(e){if(e.name!=='AbortError')report(e);}};
$('#ttlSelect').onchange=updateOptions;
function confirmDialog(title,text,yes='확인'){return new Promise(resolve=>{confirmTask=resolve;$('#confirmTitle').textContent=title;$('#confirmText').textContent=text;$('#confirmYes').textContent=yes;openDialog('#confirmDialog');});}
$('#confirmYes').onclick=()=>{const r=confirmTask;confirmTask=null;$('#confirmDialog').close();r?.(true);};
$('#confirmDialog').onclose=()=>{const r=confirmTask;confirmTask=null;r?.(false);};
function addFiles(input){let added=0;for(const file of Array.from(input||[])){if(queue.filter(q=>q.state!=='done').length>=20){toast('한 번에 최대 20개 파일을 추가할 수 있습니다.');break;}if(file.size<1||file.size>MAX){toast(file.name+': 빈 파일 또는 500 MB 초과 파일입니다.');continue;}if(queue.some(q=>q.file.name===file.name&&q.file.size===file.size&&q.file.lastModified===file.lastModified&&q.state!=='done'))continue;queue.push({id:uid(),file,state:'queued',progress:0,message:'대기 중',session:null,control:null});added++;}renderQueue();if(added)toast(added+'개 파일을 추가했습니다.');}
$('#fileInput').onchange=e=>{addFiles(e.target.files);e.target.value='';};
$('#dropzone').onclick=()=>$('#fileInput').click();$('#dropzone').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('#fileInput').click();}};
let dragDepth=0;
function fileDrag(e){return Array.from(e.dataTransfer?.types||[]).includes('Files');}
document.addEventListener('dragenter',e=>{if(!fileDrag(e))return;e.preventDefault();dragDepth++;$('#dropOverlay').hidden=false;});
document.addEventListener('dragover',e=>{if(fileDrag(e)){e.preventDefault();e.dataTransfer.dropEffect='copy';}});
document.addEventListener('dragleave',e=>{e.preventDefault();dragDepth=Math.max(0,dragDepth-1);if(!dragDepth)$('#dropOverlay').hidden=true;});
document.addEventListener('drop',e=>{if(!fileDrag(e))return;e.preventDefault();dragDepth=0;$('#dropOverlay').hidden=true;addFiles(e.dataTransfer.files);});window.addEventListener('blur',()=>{dragDepth=0;$('#dropOverlay').hidden=true;});
function renderQueue(){const el=$('#uploadQueue');el.replaceChildren();for(const q of queue){const row=document.createElement('div');row.className='queue-row';row.dataset.state=q.state;row.dataset.queueId=q.id;row.innerHTML='<div style="min-width:0"><div class="queue-name"></div><div class="queue-info"></div></div><div class="queue-actions"></div><div class="progress-line"></div>';row.querySelector('.queue-name').textContent=q.file.name;row.querySelector('.queue-info').textContent=bytes(q.file.size)+' / '+q.message;row.querySelector('.progress-line').style.width=q.progress+'%';const acts=row.querySelector('.queue-actions');if(q.state==='error'){const b=document.createElement('button');b.className='btn';b.textContent='재시도';b.dataset.retry=q.id;b.disabled=busy;acts.append(b);}if(q.state!=='done'){const b=document.createElement('button');b.className='btn icon-btn';b.textContent='[x]';b.ariaLabel=q.file.name+' 취소';b.dataset.remove=q.id;acts.append(b);}else{const b=document.createElement('span');b.textContent='[ok]';b.className='file-meta';acts.append(b);}el.append(row);}const n=queue.filter(q=>q.state==='queued'||q.state==='error').length;$('#queuedCount').textContent=n;$('#uploadBtn').disabled=busy||!n;$('#clearQueueBtn').disabled=!queue.length;$('#clearQueueBtn').textContent=busy?'전체 취소':'목록 비우기';$('#queueHeader').hidden=!queue.length;$('#queueSummary').textContent=queue.length+' files · '+bytes(queue.reduce((n,q)=>n+q.file.size,0));$('#totalProgress').textContent=queue.filter(q=>q.state==='done').length+'/'+queue.length+' 완료';$('#ttlSelect').disabled=busy;$('#setPasswordBtn').disabled=busy;}
async function discard(q){q.control?.abort();q.state='cancelled';if(q.session)try{await api('delete-file',{fileId:q.session.fileId,uploadSecret:q.session.uploadSecret});}catch{}queue=queue.filter(x=>x.id!==q.id);renderQueue();}
$('#uploadQueue').onclick=e=>{const r=e.target.closest('[data-remove]'),retry=e.target.closest('[data-retry]');if(r){const q=queue.find(x=>x.id===r.dataset.remove);if(q)discard(q);}if(retry){const q=queue.find(x=>x.id===retry.dataset.retry);if(q){q.state='queued';runUploads([q]);}}};
$('#clearQueueBtn').onclick=async()=>{if(busy){for(const q of queue)if(q.state!=='done')await discard(q);}else{for(const q of queue)if(q.state!=='done'&&q.session)await discard(q);queue=[];renderQueue();}};
function xhrUpload(url,method,blob,headers,signal,onProgress){return new Promise((resolve,reject)=>{const x=new XMLHttpRequest();let idle;const cleanup=()=>{clearTimeout(idle);signal?.removeEventListener('abort',abort);};const abort=()=>x.abort();const reset=()=>{clearTimeout(idle);idle=setTimeout(()=>x.abort(),90000);};x.open(method,url);x.timeout=180000;for(const[k,v]of Object.entries(headers))x.setRequestHeader(k,v);x.upload.onprogress=e=>{reset();if(e.lengthComputable)onProgress(e.loaded/e.total);};x.onload=()=>{cleanup();if(x.status>=200&&x.status<300)resolve();else{let d={};try{d=JSON.parse(x.responseText);}catch{}const e=new Error(d.error||d.message||'조각 전송 실패 (HTTP '+x.status+')');Object.assign(e,{status:x.status,code:d.code||'STORAGE',stage:'upload-part'});reject(e);}};x.onerror=()=>{cleanup();const e=new Error('파일 저장소에 직접 연결하지 못했습니다.');e.code='NETWORK';reject(e);};x.ontimeout=()=>{cleanup();const e=new Error('파일 전송 시간이 초과되었습니다.');e.code='TIMEOUT';reject(e);};x.onabort=()=>{cleanup();if(signal?.aborted)reject(cancelled());else{const e=new Error('파일 전송 연결이 지연되었습니다.');e.code='TIMEOUT';reject(e);}};if(signal?.aborted){reject(cancelled());return;}signal?.addEventListener('abort',abort,{once:true});reset();x.send(blob);});}
async function sendPart(q,part,plan,doneBytes){const data=q.file.slice(part.index*plan.chunkSize,part.index*plan.chunkSize+part.size,'application/octet-stream');const progress=n=>{q.progress=Math.min(99,(doneBytes+part.size*n)/q.file.size*100);renderQueue();};let last;
 for(let attempt=0;attempt<3;attempt++){if(q.control.signal.aborted)throw cancelled();if(attempt)await pause(attempt*800);try{if(!attempt&&!q.proxy){await xhrUpload(part.signedUrl,'PUT',data,{'Content-Type':'application/octet-stream'},q.control.signal,progress);}else{q.message='연결 복구 경로로 전송 중 · '+(part.index+1)+'/'+plan.parts.length;q.proxy=true;renderQueue();await xhrUpload(API+'/upload-part?file='+encodeURIComponent(q.session.fileId)+'&index='+part.index,'POST',data,{'Content-Type':'application/octet-stream','x-upload-secret':q.session.uploadSecret},q.control.signal,progress);}return;}catch(e){if(e.name==='AbortError')throw e;last=e;const resumed=await api('resume-upload',{fileId:q.session.fileId,uploadSecret:q.session.uploadSecret});if(resumed.active||resumed.parts?.find(p=>p.index===part.index)?.uploaded)return;if(e.status===413||e.status===507)throw e;}}
 throw last;
}
function ownership(){try{return JSON.parse(localStorage.getItem('opendrop-own')||'{}');}catch{return{};}}
function rememberOwn(q,end){const own=ownership();for(const id in own)if(Date.parse(own[id].expiresAt)<Date.now()+clockOffset)delete own[id];own[q.session.fileId]={secret:q.session.uploadSecret,expiresAt:end};try{localStorage.setItem('opendrop-own',JSON.stringify(own));}catch{}}
async function runUploads(targets){if(busy)return;targets=targets||queue.filter(q=>q.state==='queued'||q.state==='error');if(!targets.length)return;busy=true;$('#errorBox').hidden=true;$('#uploadMessage').textContent='업로드 중에는 이 화면을 열어 두세요.';const opts={ttl:Number($('#ttlSelect').value),password:uploadPassword};renderQueue();
 for(const q of targets){if(q.state==='cancelled'||!queue.includes(q))continue;q.state='uploading';q.control=new AbortController();q.message='업로드 준비 중';renderQueue();try{let plan;if(q.session){plan=await api('resume-upload',{fileId:q.session.fileId,uploadSecret:q.session.uploadSecret});if(plan.active){q.state='done';q.progress=100;q.message='완료';rememberOwn(q,plan.expiresAt);continue;}}else{plan=await api('init-upload',{name:q.file.name,size:q.file.size,mime:q.file.type||'application/octet-stream',...opts});q.session={fileId:plan.fileId,uploadSecret:plan.uploadSecret};}if(q.control.signal.aborted)throw cancelled();let doneBytes=0;for(const part of plan.parts){if(!part.uploaded){q.message=(part.index+1)+'/'+plan.parts.length+' 조각 전송 중';renderQueue();await sendPart(q,part,plan,doneBytes);}doneBytes+=part.size;q.progress=Math.min(99,doneBytes/q.file.size*100);renderQueue();}q.message='파일 검증 중';renderQueue();const result=await api('finalize-upload',{fileId:q.session.fileId,uploadSecret:q.session.uploadSecret});q.state='done';q.progress=100;q.message='완료 · '+remaining(result.expiresAt)+' 후 삭제';rememberOwn(q,result.expiresAt);await refresh();}catch(e){if(e.name==='AbortError'){q.state='cancelled';q.message='취소됨';if(q.session)api('delete-file',{fileId:q.session.fileId,uploadSecret:q.session.uploadSecret}).catch(()=>{});}else{q.state='error';q.message=e.message;if(e.code==='UPLOAD_EXPIRED'||e.code==='NOT_FOUND')q.session=null;report(e,'파일 업로드');}}finally{q.control=null;renderQueue();}}
 busy=false;renderQueue();const n=targets.filter(q=>q.state==='done').length;$('#uploadMessage').textContent=n+'개 파일 업로드 완료'+(targets.some(q=>q.state==='error')?' · 실패한 파일은 재시도로 이어 올릴 수 있습니다.':'');refresh();
}
$('#uploadBtn').onclick=()=>runUploads();
function renderFiles(){const own=ownership(),el=$('#fileList');el.replaceChildren();for(const f of files){const row=document.createElement('div');row.className='file-row';row.dataset.fileId=f.id;const locked=f.locked?'[#] 비밀번호':'[ ] 공개';row.innerHTML='<label class="check-cell"><input type="checkbox" data-select="'+escape(f.id)+'" aria-label="'+escape(f.name)+' 선택" '+(selected.has(f.id)?'checked':'')+'></label><div style="min-width:0"><div class="file-name"></div><div class="file-secondary"></div></div><div class="file-meta size-cell"></div><div class="file-meta expiry-cell"></div><div class="file-actions"><button class="btn" data-action="preview">미리보기</button><button class="btn" data-action="download">[↓] 받기</button><button class="btn icon-btn" data-action="share" aria-label="공유 링크 복사">[↗]</button></div>';row.querySelector('.file-name').textContent=f.name;row.querySelector('.file-name').title=f.name;row.querySelector('.file-secondary').textContent=locked+' · '+bytes(f.size)+' · '+remaining(f.expiresAt)+' 남음';row.querySelector('.size-cell').textContent=bytes(f.size);row.querySelector('.expiry-cell').textContent=remaining(f.expiresAt);if(own[f.id]){const b=document.createElement('button');b.className='btn icon-btn';b.dataset.action='delete';b.ariaLabel='내가 올린 파일 삭제';b.textContent='[-]';row.querySelector('.file-actions').append(b);}el.append(row);}$('#fileCount').textContent=files.length+' files'+(files.length===100?' / 최대 100개 표시':'');$('#emptyState').hidden=!!files.length;$('#emptyState .empty-symbol').textContent='[ ]';$('#emptyText').textContent=$('#searchInput').value?'검색 결과가 없습니다.':'아직 공유된 파일이 없습니다.';$('#emptyHelp').textContent=$('#searchInput').value?'다른 이름으로 검색해 보세요.':'파일을 올리면 이곳에 표시됩니다.';selectionUi();}
async function loadFiles(){const serial=++loadSerial;const q=new URLSearchParams({q:$('#searchInput').value.trim(),sort:$('#sortSelect').value});const d=await api('files?'+q);if(serial!==loadSerial)return;files=d.files||[];selected=new Set([...selected].filter(id=>files.some(f=>f.id===id)));renderFiles();}
async function refresh(){try{await Promise.all([loadFiles(),api('status').then(s=>{$('#storagePill').textContent='사용 '+bytes(s.reservedBytes)+' / '+bytes(s.reserveLimitBytes);})]);$('#connectionStatus').textContent='[ok] 연결됨 · 자동 삭제 활성';}catch(e){$('#connectionStatus').textContent='[!] 연결 확인 필요';$('#emptyText').textContent='파일 목록을 불러오지 못했습니다.';$('#emptyHelp').textContent='새로고침으로 다시 연결해 주세요.';report(e,'연결');}}
function selectionUi(){$('#selectionCount').textContent=selected.size+'개 선택';$('#zipBtn').disabled=!selected.size;$('#clearSelectionBtn').disabled=!selected.size;$('#selectAll').checked=!!files.length&&files.every(f=>selected.has(f.id));$('#selectAll').indeterminate=!!selected.size&&!$('#selectAll').checked;}
$('#fileList').onchange=e=>{if(!e.target.dataset.select)return;e.target.checked?selected.add(e.target.dataset.select):selected.delete(e.target.dataset.select);selectionUi();};$('#selectAll').onchange=e=>{e.target.checked?files.forEach(f=>selected.add(f.id)):selected.clear();renderFiles();};$('#clearSelectionBtn').onclick=()=>{selected.clear();renderFiles();};
async function getAccess(f){const a=accessCache.get(f.id);if(a&&Date.parse(a.tokenExpiresAt)>Date.now()+clockOffset+10000)return a;if(f.locked)return passwordDialog('unlock',f);const v=await api('access',{fileId:f.id});accessCache.set(f.id,v);return v;}
async function manifest(f,count=false){const a=await getAccess(f),m=await api('manifest',{fileId:f.id,token:a.token,count});return{...m,_token:a.token,_clockOffset:clockOffset};}
async function registerTransfer(manifests,{name,zip=false,inline=false,mime='application/octet-stream'}){const worker=await workerReady;if(!worker)return null;const id=uid(),channel=new MessageChannel();const ok=new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(new Error('다운로드 준비 시간이 초과되었습니다.')),6000);channel.port1.onmessage=e=>{clearTimeout(t);channel.port1.close();e.data.ok?resolve(true):reject(new Error(e.data.error));};});worker.postMessage({type:'register-transfer',job:{id,name,zip,inline,mime,manifests}},[channel.port2]);await ok;return'/__transfer/'+id+'/'+encodeURIComponent(T.filename(name));}
function saveUrl(url,name){const a=document.createElement('a');a.href=url;a.download=T.filename(name);a.rel='noopener';document.body.append(a);a.click();a.remove();}
async function fallbackBlob(ms,zip){const total=ms.reduce((n,m)=>n+Number(m.file.size),0);if(total>128*1024*1024&&!await confirmDialog('[i] 호환 다운로드','이 브라우저는 스트리밍 저장을 지원하지 않습니다. '+bytes(total)+'를 메모리에 모아 저장하므로 메모리가 부족할 수 있습니다. Chrome/Edge 사용을 권장합니다. 계속할까요?','계속'))throw cancelled();if(!zip)return T.blob(ms[0]);const out=[];for await(const b of T.zipBytes(ms))out.push(b);return new Blob(out,{type:'application/zip'});}
async function download(f){const m=await manifest(f,true);let url=await registerTransfer([m],{name:f.name});if(!url){const blob=await fallbackBlob([m],false);url=URL.createObjectURL(blob);setTimeout(()=>URL.revokeObjectURL(url),120000);}saveUrl(url,f.name);toast('다운로드를 시작했습니다. 브라우저 다운로드 목록을 확인하세요.');}
async function copy(text){try{await navigator.clipboard.writeText(text);}catch{const t=document.createElement('textarea');t.value=text;t.style.position='fixed';t.style.opacity='0';document.body.append(t);t.select();const ok=document.execCommand('copy');t.remove();if(!ok)throw new Error('클립보드에 접근하지 못했습니다.');}toast('복사했습니다.');}
function previewType(f){const ext=f.name.split('.').pop().toLowerCase();if(['html','htm','svg','xml','js','mjs','json','css','txt','md','csv','py','java','c','cpp','h','log','yaml','yml'].includes(ext)||f.mime.startsWith('text/'))return['text','text/plain'];const mime=f.mime.toLowerCase();if(['image/png','image/jpeg','image/gif','image/webp','image/avif','image/bmp'].includes(mime))return['image',mime];if(['video/mp4','video/webm','video/ogg'].includes(mime))return['video',mime];if(['audio/mpeg','audio/mp4','audio/ogg','audio/wav','audio/x-wav','audio/flac','audio/webm'].includes(mime))return['audio',mime];if(mime==='application/pdf'||ext==='pdf')return['pdf','application/pdf'];return['unknown','application/octet-stream'];}
async function preview(f){const m=await manifest(f),[type,mime]=previewType(f);previewFile=f;$('#previewName').textContent=f.name;$('#previewMeta').textContent=bytes(f.size)+' · '+remaining(f.expiresAt)+' 남음';$('#previewNote').textContent='';const body=$('#previewBody');body.textContent='미리보기를 준비하는 중입니다.';openDialog('#previewDialog');try{if(type==='unknown'){body.textContent='이 형식은 미리보기를 지원하지 않습니다. 다운로드해서 열어 주세요.';return;}if(type==='text'){const chunks=[];for await(const b of T.fileBytes(m,0,Math.min(f.size,204800)-1))chunks.push(b);const pre=document.createElement('pre');pre.textContent=await new Blob(chunks).text();body.replaceChildren(pre);$('#previewNote').textContent=f.size>204800?'처음 200 KB만 표시합니다.':'텍스트는 실행하지 않고 표시합니다.';return;}let url=await registerTransfer([m],{name:f.name,inline:true,mime});if(!url){url=URL.createObjectURL(await fallbackBlob([m],false));previewUrls.push(url);}if(!$('#previewDialog').open)return;let el;if(type==='image'){el=document.createElement('img');el.alt=f.name;}else if(type==='pdf'){el=document.createElement('iframe');el.title='PDF 미리보기';}else{el=document.createElement(type);el.controls=true;el.preload='metadata';el.setAttribute('playsinline','');}el.src=url;body.replaceChildren(el);$('#previewNote').textContent=type==='pdf'?'PDF가 표시되지 않으면 다운로드해서 열어 주세요.':'지원 여부는 파일 형식과 브라우저 코덱에 따라 달라집니다.';}catch(e){body.textContent=e.message;report(e,'미리보기');}}
$('#previewDialog').onclose=()=>{$('#previewBody').replaceChildren();for(const u of previewUrls)URL.revokeObjectURL(u);previewUrls=[];previewFile=null;};$('#previewDownload').onclick=async()=>{if(!previewFile)return;try{await download(previewFile);}catch(e){report(e,'다운로드');}};
$('#fileList').onclick=async e=>{const btn=e.target.closest('[data-action]');if(!btn)return;const f=files.find(f=>f.id===btn.closest('[data-file-id]').dataset.fileId);if(!f)return;btn.disabled=true;try{const action=btn.dataset.action;if(action==='download')await download(f);if(action==='preview')await preview(f);if(action==='share')await copy(location.origin+'/?file='+encodeURIComponent(f.id));if(action==='delete'){if(await confirmDialog('[-] 내 파일 삭제',f.name+' 파일을 지금 삭제할까요?','삭제')){const own=ownership();await api('delete-file',{fileId:f.id,uploadSecret:own[f.id]?.secret});delete own[f.id];try{localStorage.setItem('opendrop-own',JSON.stringify(own));}catch{}await refresh();toast('파일을 삭제했습니다.');}}}catch(err){if(err.name!=='AbortError'){report(err,btn.dataset.action==='preview'?'미리보기':'파일 작업');toast(err.message);}}finally{btn.disabled=false;}};
$('#zipBtn').onclick=async()=>{const target=files.filter(f=>selected.has(f.id));if(!target.length)return;$('#zipBtn').disabled=true;try{const ms=[];for(const f of target)ms.push(await manifest(f,true));let url=await registerTransfer(ms,{name:'OpenDrop.zip',zip:true});if(!url){url=URL.createObjectURL(await fallbackBlob(ms,true));setTimeout(()=>URL.revokeObjectURL(url),120000);}saveUrl(url,'OpenDrop.zip');toast(target.length+'개 파일의 ZIP 다운로드를 시작했습니다.');}catch(e){report(e,'ZIP 다운로드');}finally{selectionUi();}};
$('#searchInput').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>loadFiles().catch(e=>report(e,'검색')),250);};$('#sortSelect').onchange=()=>loadFiles().catch(e=>report(e,'정렬'));$('#refreshBtn').onclick=()=>{$('#errorBox').hidden=true;refresh();};$('#copyErrorBtn').onclick=()=>copy($('#errorDetail').textContent).catch(e=>toast(e.message));
document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)&&!document.querySelector('dialog[open]')){e.preventDefault();$('#searchInput').focus();}});
window.addEventListener('online',()=>{toast('인터넷에 다시 연결되었습니다.');refresh();});window.addEventListener('offline',()=>{$('#connectionStatus').textContent='[!] 오프라인';toast('인터넷 연결이 끊겼습니다. 업로드는 재시도로 이어 올릴 수 있습니다.');});
setInterval(()=>{if(!document.hidden&&!busy&&!document.querySelector('dialog[open]'))refresh();},60000);
setInterval(()=>{if(!document.hidden){const before=files.length;files=files.filter(f=>Date.parse(f.expiresAt)>Date.now()+clockOffset);if(before!==files.length){selected=new Set([...selected].filter(id=>files.some(f=>f.id===id)));renderFiles();}else for(const row of document.querySelectorAll('[data-file-id]')){const f=files.find(f=>f.id===row.dataset.fileId);if(f)row.querySelector('.expiry-cell').textContent=remaining(f.expiresAt);}}},15000);
window.addEventListener('beforeunload',e=>{if(busy){e.preventDefault();e.returnValue='';}});
updateOptions();renderQueue();refresh().then(async()=>{const id=new URLSearchParams(location.search).get('file');if(id)try{const d=await api('file?file='+encodeURIComponent(id));await preview(d.file);}catch(e){report(e,'공유 파일');}});
