import chromium from '@sparticuz/chromium';import puppeteer from 'puppeteer-core';import {createServer} from 'node:http';import {readFile,writeFile,mkdir,readdir} from 'node:fs/promises';import {resolve,extname} from 'node:path';
const root=process.cwd(),dir='/tmp/od-probe';await mkdir(dir,{recursive:true});const report={events:[],errors:[],checks:[]};
const server=createServer(async(req,res)=>{try{let p=new URL(req.url,'http://local').pathname;const b=await readFile(resolve(root,'.'+(p==='/'?'/index.html':p)));res.setHeader('Content-Type',extname(p)==='.js'?'application/javascript':'text/html; charset=utf-8');res.end(b);}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(4181,'127.0.0.1',r));let browser,page,session;
try{chromium.setGraphicsMode=false;browser=await puppeteer.launch({args:chromium.args,executablePath:await chromium.executablePath(),headless:'shell'});page=await browser.newPage();await page.setViewport({width:390,height:844,isMobile:true,hasTouch:true});page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text().replace(/\?[^ ]*/g,'?[redacted]'));});page.on('pageerror',e=>report.errors.push(e.message));
const client=await page.createCDPSession();await client.send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:dir,eventsEnabled:true});client.on('Browser.downloadWillBegin',e=>report.events.push({type:'begin',guid:e.guid,name:e.suggestedFilename,url:e.url}));client.on('Browser.downloadProgress',e=>{if(e.state!=='inProgress')report.events.push({type:'end',...e});});
await page.goto('http://127.0.0.1:4181',{waitUntil:'networkidle0'});await page.waitForFunction(()=>document.querySelector('#connectionStatus').textContent.includes('[ok]'));
const name='probe-'+Date.now()+'.txt';const output=await page.evaluate(async name=>{const value='test download\n';const s=await api('init-upload',{name,size:new TextEncoder().encode(value).length,mime:'text/plain',ttl:600});const r=await fetch(s.parts[0].signedUrl,{method:'PUT',headers:{'Content-Type':'application/octet-stream'},body:value});if(!r.ok)throw Error('upload '+r.status);await api('finalize-upload',{fileId:s.fileId,uploadSecret:s.uploadSecret});await refresh();return s;},name);session=output;
const probe=await page.evaluate(async id=>{const f=files.find(f=>f.id===id),m=await manifest(f),v=await registerTransfer([m],{name:f.name});const r=await fetch(v);return{sw:!!navigator.serviceWorker.controller,virtualUrl:v,status:r.status,headers:Object.fromEntries(r.headers),body:await r.text()};},session.fileId);report.checks.push({step:'virtual-fetch',...probe});
const selector='[data-file-id="'+session.fileId+'"] [data-action="download"]';await page.$eval(selector,e=>e.scrollIntoView({block:'center'}));const hit=await page.$eval(selector,e=>{const r=e.getBoundingClientRect();return{rect:{x:r.x,y:r.y,w:r.width,h:r.height},top:document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.outerHTML};});report.checks.push({step:'hit-target',...hit});
await page.click(selector);await new Promise(r=>setTimeout(r,6000));report.checks.push({step:'after-click',files:await readdir(dir),url:page.url(),ui:await page.$eval('#errorDetail',e=>e.textContent)});
await page.evaluate(async id=>{const f=files.find(f=>f.id===id);await download(f);},session.fileId);await new Promise(r=>setTimeout(r,6000));report.checks.push({step:'after-programmatic',files:await readdir(dir)});
const p=await page.evaluate(async id=>{const f=files.find(f=>f.id===id),m=await manifest(f);return await registerTransfer([m],{name:f.name});},session.fileId);await page.evaluate(p=>{const iframe=document.createElement('iframe');iframe.src=p;iframe.hidden=true;document.body.appendChild(iframe);},p);await new Promise(r=>setTimeout(r,6000));report.checks.push({step:'after-iframe',files:await readdir(dir)});
}catch(e){report.error=String(e.stack||e);}finally{if(page&&session)try{await page.evaluate(async s=>await api('delete-file',{fileId:s.fileId,uploadSecret:s.uploadSecret}),session);}catch{}if(browser)await browser.close();server.close();console.log('OPENDROP_DOWNLOAD_PROBE '+JSON.stringify(report));}
